package com.abcproduct.org.ranc.AbcProduct.domain.model;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public class TestTableModel {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TestTable.id
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TestTable.name
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TestTable.id
	 * @return  the value of TestTable.id
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TestTable.id
	 * @param id  the value for TestTable.id
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TestTable.name
	 * @return  the value of TestTable.name
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TestTable.name
	 * @param name  the value for TestTable.name
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	@Override
	public String toString() {
		return "TestTableModel [id=" + id + ", name=" + name + "]";
	}
}