package com.abcproduct.org.ranc.AbcProduct.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.abcproduct.org.ranc.AbcProduct.domain.model.TestTableModel;
import com.abcproduct.org.ranc.AbcProduct.domain.model.TestTableModelExample;

@Mapper
public interface TestTableRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	long countByExample(TestTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	int deleteByExample(TestTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	int insert(TestTableModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	int insertSelective(TestTableModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	List<TestTableModel> selectByExample(TestTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	TestTableModel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	int updateByExampleSelective(@Param("record") TestTableModel record,
			@Param("example") TestTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	int updateByExample(@Param("record") TestTableModel record, @Param("example") TestTableModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	int updateByPrimaryKeySelective(TestTableModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TestTable
	 * @mbg.generated  Mon Feb 08 13:03:49 JST 2021
	 */
	int updateByPrimaryKey(TestTableModel record);
}